# Dependencies
markdown:         redcarpet
#highlighter: pygments
highlighter:      null

# Permalinks
permalink:        pretty

# Setup
title:            Sagang Wee
tagline:          'Personal Website'
description:      'Studies Computer Science at University of California, Berkeley'
url:              http://sagangwee.xyz
baseurl:          /
# <a href="http://jekyllrb.com" target="_blank">Jekyll</a>

author:
  name:           'Sagang Wee'
  url:            https://github.com/sagangwee

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/sagangwee

paginate_path: "page:num"

gems:
  - jekyll-paginate
  - redcarpet
  - jekyll-gist
  - pygments.rb

#sudo apt-get install python-pygments
#sudo gem install pygments.rb
#sudo apt-get install ruby-dev
#jekyll serve --host 0.0.0.0